
import java.io.FileWriter;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author PaulKusuma
 */
public class ChangePass extends javax.swing.JFrame {

    /**
     * Creates new form ChangePass
     */
    public ChangePass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userInput = new javax.swing.JTextField();
        labelInputUser = new javax.swing.JLabel();
        pwInputLama = new javax.swing.JPasswordField();
        pwInputBaru = new javax.swing.JPasswordField();
        labelInputPwLama = new javax.swing.JLabel();
        labelInputPwBaru = new javax.swing.JLabel();
        ButtonConfirm = new javax.swing.JButton();
        labelChangePw = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userInputActionPerformed(evt);
            }
        });

        labelInputUser.setText("Username");

        pwInputLama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwInputLamaActionPerformed(evt);
            }
        });

        pwInputBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwInputBaruActionPerformed(evt);
            }
        });

        labelInputPwLama.setText("PassLama");

        labelInputPwBaru.setText("PassBaru");

        ButtonConfirm.setText("Confirm");
        ButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConfirmActionPerformed(evt);
            }
        });

        labelChangePw.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelChangePw.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelChangePw.setText("Change Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelChangePw)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(labelInputPwBaru)
                                    .addGap(53, 53, 53))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelInputUser)
                                    .addGap(50, 50, 50)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelInputPwLama)
                                .addGap(53, 53, 53)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ButtonConfirm)
                            .addComponent(pwInputBaru, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(pwInputLama)
                            .addComponent(userInput))
                        .addGap(117, 117, 117))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labelChangePw, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(labelInputUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(userInput, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwInputLama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelInputPwLama))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelInputPwBaru)
                    .addComponent(pwInputBaru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ButtonConfirm)
                .addGap(97, 97, 97))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userInputActionPerformed
        // TODO add your handling code here:
        pwInputLama.requestFocusInWindow();
    }//GEN-LAST:event_userInputActionPerformed

    private void pwInputLamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwInputLamaActionPerformed
        // TODO add your handling code here:
        pwInputBaru.requestFocusInWindow();
    }//GEN-LAST:event_pwInputLamaActionPerformed

    private void ButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConfirmActionPerformed
        // TODO add your handling code here:
        String U, PL, PB;
        U = userInput.getText();
        PL = pwInputLama.getText();
        PB = pwInputBaru.getText();
        if (U.equalsIgnoreCase("") || PL.equalsIgnoreCase("") || 
                PB.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Harap masukkan Username"
                    + " dan Password");
            userInput.requestFocus();
        } else {
            if (PL.equalsIgnoreCase(PB)) {
                JOptionPane.showMessageDialog(null, "Password Lama Sama dengan "
                        + "Password Baru");
            } else {
                try {
                    FileWriter f = new FileWriter("pass.txt");
                    f.write(U);
                    f.write(" " + PB);
                    f.close();

                } catch (Exception e) {
                    e.getStackTrace();
                }
                this.dispose();
                new Login().setVisible(true);
            }
        }
    }//GEN-LAST:event_ButtonConfirmActionPerformed

    private void pwInputBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwInputBaruActionPerformed
        // TODO add your handling code here:
        ButtonConfirm.doClick();
    }//GEN-LAST:event_pwInputBaruActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ChangePass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonConfirm;
    private javax.swing.JLabel labelChangePw;
    private javax.swing.JLabel labelInputPwBaru;
    private javax.swing.JLabel labelInputPwLama;
    private javax.swing.JLabel labelInputUser;
    private javax.swing.JPasswordField pwInputBaru;
    private javax.swing.JPasswordField pwInputLama;
    private javax.swing.JTextField userInput;
    // End of variables declaration//GEN-END:variables
}
